### ISSUE TITLE
Erreur de segmentation

### ISSUE THREAD

**Issue by dcjona** [capsule-corp-ternoa/ternoa-node#320]
dcjona@nuc:~$ sudo /home/dcjona/ternoascript/ternoa-node/target/release/ternoa --name "SecureTernoaGuardian" --chain mainnet --base-path /block/chain/node-data --ws-max-connections 1000 --prometheus-port 9615 --validator --telemetry-url "wss://telemetry.polkadot.io/submit/ 0" --state-pruning archive
2024-03-18 09:42:44 Ternoa Node
2024-03-18 09:42:44 ✌️  version 1.1.1
2024-03-18 09:42:44 ❤️  by Ternoa, 2020-2024
2024-03-18 09:42:44 📋 Chain specification: Ternoa Mainnet
2024-03-18 09:42:44 🏷  Node name: SecureTernoaGuardian
2024-03-18 09:42:44 👤 Role: AUTHORITY
2024-03-18 09:42:44 💾 Database: RocksDb at /block/chain/node-data/chains/mainnet-live/db/full
2024-03-18 09:42:44 ⛓  Native runtime: mainnet-21 (mainnet-0.tx1.au1)

====================

Version: 1.1.1

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/core/src/panicking.rs:142:14
   6: core::result::unwrap_failed
             at /rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/core/src/result.rs:1814:5
   7: <sp_state_machine::ext::Ext<H,B> as sp_externalities::Externalities>::storage
   8: <&mut dyn sp_externalities::Externalities as sp_io::storage::Storage>::get_version_1
   9: sp_externalities::scope_limited::with_externalities
  10: tracing::span::Span::in_scope
  11: sp_io::storage::get_version_1
  12: sp_io::storage::ExtStorageGetVersion1::call
  13: <sc_executor_wasmtime::imports::Registry as sp_wasm_interface::HostFunctionRegistry>::with_function_context
  14: std::panicking::try
  15: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1),R>>::into_func::wasm_to_host_shim
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: wasmtime_runtime::traphandlers::catch_traps::call_closure
  21: wasmtime_setjmp
  22: wasmtime_runtime::traphandlers::<impl wasmtime_runtime::traphandlers::call_thread_state::CallThreadState>::with
  23: wasmtime_runtime::traphandlers::catch_traps
  24: wasmtime::func::invoke_wasm_and_catch_traps
  25: wasmtime::func::typed::TypedFunc<Params,Results>::call
  26: sc_executor_wasmtime::instance_wrapper::EntryPoint::call
  27: sc_executor_wasmtime::runtime::perform_call
  28: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call_with_allocation_stats
  29: sc_executor_common::wasm_runtime::WasmInstance::call_export
  30: std::panicking::try
  31: std::thread::local::LocalKey<T>::with
  32: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
  33: sc_executor::wasm_runtime::RuntimeCache::with_instance
  34: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
  35: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
  36: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
  37: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  38: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  39: <mainnet_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::__runtime_api_internal_call_api_at
  40: sp_consensus_babe::BabeApi::configuration
  41: ternoa_service::new_partial
  42: ternoa_service::new_full
  43: tokio::runtime::park::CachedParkThread::block_on
  44: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  45: tokio::runtime::runtime::Runtime::block_on
  46: sc_cli::runner::Runner<C>::run_node_until_exit
  47: ternoa_cli::command::run
  48: ternoa::main
  49: std::sys_common::backtrace::__rust_begin_short_backtrace
  50: std::rt::lang_start::{{closure}}
  51: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/core/src/ops/function.rs:280:13
      std::panicking::try::do_call
             at /rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at /rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/rt.rs:128:20
  52: main
  53: __libc_start_main
  54: _start

Thread 'main' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0x0035d5792a25d8a3ae456f61d5e261968471d3a51d47340744cf5da510d6c15d"', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/a3ed011/primitives/state-machine/src/ext.rs:189

This is a bug. Please report it at:

        https://github.com/capsule-corp-ternoa/chain/issues

Erreur de segmentation

**Comment by Immanuel-john** [comment]
Hi @dcjona please use the binary from [here](https://github.com/capsule-corp-ternoa/ternoa-node/releases/tag/v1.3.2) for now. we are working on this issue.

**Comment by dcjona** [comment]
hi thanks will try

**Comment by Arimav2nd** [comment]
I use 1.3.2 version and had the same issue : 
```
mars 29 20:22:46 archive06 ternoa[364452]: 2024-03-29 20:22:46 Ternoa Node
mars 29 20:22:46 archive06 ternoa[364452]: 2024-03-29 20:22:46 ✌️  version 1.1.1
mars 29 20:22:46 archive06 ternoa[364452]: 2024-03-29 20:22:46 ❤️  by Ternoa, 2020-2024
mars 29 20:22:46 archive06 ternoa[364452]: 2024-03-29 20:22:46 📋 Chain specification: Ternoa Mainnet
mars 29 20:22:46 archive06 ternoa[364452]: 2024-03-29 20:22:46 🏷  Node name: Mei-Lee
mars 29 20:22:46 archive06 ternoa[364452]: 2024-03-29 20:22:46 👤 Role: FULL
mars 29 20:22:46 archive06 ternoa[364452]: 2024-03-29 20:22:46 💾 Database: RocksDb at /block/chain/node-data/chains/mainnet-live/db/full
mars 29 20:22:46 archive06 ternoa[364452]: 2024-03-29 20:22:46 ⛓  Native runtime: mainnet-21 (mainnet-0.tx1.au1)
mars 29 20:22:50 archive06 ternoa[364452]: ====================
mars 29 20:22:50 archive06 ternoa[364452]: Version: 1.1.1
mars 29 20:22:50 archive06 ternoa[364452]:    0: sp_panic_handler::set::{{closure}}
mars 29 20:22:50 archive06 ternoa[364452]:    1: std::panicking::rust_panic_with_hook
mars 29 20:22:50 archive06 ternoa[364452]:              at rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/panicking.rs:702:17
mars 29 20:22:50 archive06 ternoa[364452]:    2: std::panicking::begin_panic_handler::{{closure}}
mars 29 20:22:50 archive06 ternoa[364452]:              at rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/panicking.rs:588:13
mars 29 20:22:50 archive06 ternoa[364452]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
mars 29 20:22:50 archive06 ternoa[364452]:              at rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/sys_common/backtrace.rs:138:18
mars 29 20:22:50 archive06 ternoa[364452]:    4: rust_begin_unwind
mars 29 20:22:50 archive06 ternoa[364452]:              at rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/panicking.rs:584:5
mars 29 20:22:50 archive06 ternoa[364452]:    5: core::panicking::panic_fmt
mars 29 20:22:50 archive06 ternoa[364452]:              at rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/core/src/panicking.rs:142:14
mars 29 20:22:50 archive06 ternoa[364452]:    6: core::result::unwrap_failed
mars 29 20:22:50 archive06 ternoa[364452]:              at rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/core/src/result.rs:1814:5
mars 29 20:22:50 archive06 ternoa[364452]:    7: <sp_state_machine::ext::Ext<H,B> as sp_externalities::Externalities>::storage
mars 29 20:22:50 archive06 ternoa[364452]:    8: <&mut dyn sp_externalities::Externalities as sp_io::storage::Storage>::get_version_1
mars 29 20:22:50 archive06 ternoa[364452]:    9: sp_externalities::scope_limited::with_externalities
mars 29 20:22:50 archive06 ternoa[364452]:   10: tracing::span::Span::in_scope
mars 29 20:22:50 archive06 ternoa[364452]:   11: sp_io::storage::get_version_1
mars 29 20:22:50 archive06 ternoa[364452]:   12: sp_io::storage::ExtStorageGetVersion1::call
mars 29 20:22:50 archive06 ternoa[364452]:   13: <sc_executor_wasmtime::imports::Registry as sp_wasm_interface::HostFunctionRegistry>::with_function_context
mars 29 20:22:50 archive06 ternoa[364452]:   14: std::panicking::try
mars 29 20:22:50 archive06 ternoa[364452]:   15: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1),R>>::into_func::wasm_to_host_shim
mars 29 20:22:50 archive06 ternoa[364452]:   16: <unknown>
mars 29 20:22:50 archive06 ternoa[364452]:   17: <unknown>
mars 29 20:22:50 archive06 ternoa[364452]:   18: <unknown>
mars 29 20:22:50 archive06 ternoa[364452]:   19: <unknown>
mars 29 20:22:50 archive06 ternoa[364452]:   20: wasmtime_runtime::traphandlers::catch_traps::call_closure
mars 29 20:22:50 archive06 ternoa[364452]:   21: wasmtime_setjmp
mars 29 20:22:50 archive06 ternoa[364452]:   22: wasmtime_runtime::traphandlers::<impl wasmtime_runtime::traphandlers::call_thread_state::CallThreadState>::with
mars 29 20:22:50 archive06 ternoa[364452]:   23: wasmtime_runtime::traphandlers::catch_traps
mars 29 20:22:50 archive06 ternoa[364452]:   24: wasmtime::func::invoke_wasm_and_catch_traps
mars 29 20:22:50 archive06 ternoa[364452]:   25: wasmtime::func::typed::TypedFunc<Params,Results>::call
mars 29 20:22:50 archive06 ternoa[364452]:   26: sc_executor_wasmtime::instance_wrapper::EntryPoint::call
mars 29 20:22:50 archive06 ternoa[364452]:   27: sc_executor_wasmtime::runtime::perform_call
mars 29 20:22:50 archive06 ternoa[364452]:   28: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call_with_allocation_stats
mars 29 20:22:50 archive06 ternoa[364452]:   29: sc_executor_common::wasm_runtime::WasmInstance::call_export
mars 29 20:22:50 archive06 ternoa[364452]:   30: std::panicking::try
mars 29 20:22:50 archive06 ternoa[364452]:   31: std::thread::local::LocalKey<T>::with
mars 29 20:22:50 archive06 ternoa[364452]:   32: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
mars 29 20:22:50 archive06 ternoa[364452]:   33: sc_executor::wasm_runtime::RuntimeCache::with_instance
mars 29 20:22:50 archive06 ternoa[364452]:   34: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
mars 29 20:22:50 archive06 ternoa[364452]:   35: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
mars 29 20:22:50 archive06 ternoa[364452]:   36: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
mars 29 20:22:50 archive06 ternoa[364452]:   37: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
mars 29 20:22:50 archive06 ternoa[364452]:   38: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
mars 29 20:22:50 archive06 ternoa[364452]:   39: <mainnet_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_offchain::OffchainWorkerApi<__SR_API_BLOCK__>>::__runtime_api_internal_call_api_at
mars 29 20:22:50 archive06 ternoa[364452]:   40: sp_consensus_babe::BabeApi::configuration
mars 29 20:22:50 archive06 ternoa[364452]:   41: ternoa_service::new_partial
mars 29 20:22:50 archive06 ternoa[364452]:   42: ternoa_service::new_full
mars 29 20:22:50 archive06 ternoa[364452]:   43: tokio::runtime::park::CachedParkThread::block_on
mars 29 20:22:50 archive06 ternoa[364452]:   44: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
mars 29 20:22:50 archive06 ternoa[364452]:   45: tokio::runtime::runtime::Runtime::block_on
mars 29 20:22:50 archive06 ternoa[364452]:   46: sc_cli::runner::Runner<C>::run_node_until_exit
mars 29 20:22:50 archive06 ternoa[364452]:   47: ternoa_cli::command::run
mars 29 20:22:50 archive06 ternoa[364452]:   48: ternoa::main
mars 29 20:22:50 archive06 ternoa[364452]:   49: std::sys_common::backtrace::__rust_begin_short_backtrace
mars 29 20:22:50 archive06 ternoa[364452]:   50: std::rt::lang_start::{{closure}}
mars 29 20:22:50 archive06 ternoa[364452]:   51: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
mars 29 20:22:50 archive06 ternoa[364452]:              at rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/core/src/ops/function.rs:280:13
mars 29 20:22:50 archive06 ternoa[364452]:       std::panicking::try::do_call
mars 29 20:22:50 archive06 ternoa[364452]:              at rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/panicking.rs:492:40
mars 29 20:22:50 archive06 ternoa[364452]:       std::panicking::try
mars 29 20:22:50 archive06 ternoa[364452]:              at rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/panicking.rs:456:19
mars 29 20:22:50 archive06 ternoa[364452]:       std::panic::catch_unwind
mars 29 20:22:50 archive06 ternoa[364452]:              at rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/panic.rs:137:14
mars 29 20:22:50 archive06 ternoa[364452]:       std::rt::lang_start_internal::{{closure}}
mars 29 20:22:50 archive06 ternoa[364452]:              at rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/rt.rs:128:48
mars 29 20:22:50 archive06 ternoa[364452]:       std::panicking::try::do_call
mars 29 20:22:50 archive06 ternoa[364452]:              at rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/panicking.rs:492:40
mars 29 20:22:50 archive06 ternoa[364452]:       std::panicking::try
mars 29 20:22:50 archive06 ternoa[364452]:              at rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/panicking.rs:456:19
mars 29 20:22:50 archive06 ternoa[364452]:       std::panic::catch_unwind
mars 29 20:22:50 archive06 ternoa[364452]:              at rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/panic.rs:137:14
mars 29 20:22:50 archive06 ternoa[364452]:       std::rt::lang_start_internal
mars 29 20:22:50 archive06 ternoa[364452]:              at rustc/34a6cae28e7013ff0e640026a8e46f315426829d/library/std/src/rt.rs:128:20
mars 29 20:22:50 archive06 ternoa[364452]:   52: main
mars 29 20:22:50 archive06 ternoa[364452]:   53: <unknown>
mars 29 20:22:50 archive06 ternoa[364452]:   54: __libc_start_main
mars 29 20:22:50 archive06 ternoa[364452]:   55: _start
mars 29 20:22:50 archive06 ternoa[364452]: Thread 'main' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0xb3474e63fb30570ad0acd95787893e999a931d9d88f688a21c0d84d139c806e5"', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/a3ed011/primitives/state-machine/src/ext.rs:189
mars 29 20:22:50 archive06 ternoa[364452]: This is a bug. Please report it at:
mars 29 20:22:50 archive06 ternoa[364452]:         https://github.com/capsule-corp-ternoa/chain/issues
mars 29 20:22:50 archive06 systemd[1]: ternoa.service: Main process exited, code=killed, status=11/SEGV
mars 29 20:22:50 archive06 systemd[1]: ternoa.service: Failed with result 'signal'.
```
Only way to fix were to erase /block folder and resync
